# Generated by Django 5.0.7 on 2024-10-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_studentlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='user',
        ),
    ]
